name: pyg
channels:
  - pyg
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.10.18
  - debugpy=1.8.15
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - faiss=1.9.0
  - filelock=3.18.0
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kaldi=5.5.1112
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=20.1.8
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libfaiss=1.9.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.24
  - libpng=1.6.50
  - libprotobuf=5.28.3
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libuv=1.51.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - numpy=1.26.4
  - openfst=1.8.3
  - openjpeg=2.5.3
  - openssl=3.5.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cluster=1.6.3
  - pytorch-scatter=2.1.2
  - pytorch-sparse=0.6.18
  - pytorch-spline-conv=1.2.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - readline=8.2
  - requests=2.32.4
  - scipy=1.15.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.8
  - stack_data=0.6.3
  - sympy=1.14.0
  - tk=8.6.13
  - torch-geometric=2.6.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - biopython==1.85
      - cachetools==6.2.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - duckdb==1.3.2
      - fonttools==4.59.1
      - google-auth==2.45.0
      - google-genai==1.55.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - ipywidgets==8.1.7
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - littleutils==0.2.4
      - matplotlib==3.10.5
      - ogb==1.3.6
      - outdated==0.2.2
      - pandas==2.3.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pytz==2025.2
      - regex==2025.10.23
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - sniffio==1.3.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - transformers==4.57.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
prefix: /Users/shutt/miniforge3/envs/pyg
